# Generated by Django 3.2 on 2022-10-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
