# Generated by Django 3.2 on 2022-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221015_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
