# Generated by Django 3.2.5 on 2022-08-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_contact_isread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='role',
        ),
    ]
